name: github

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  example-job:
    runs-on: ubuntu-latest
    continue-on-error
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: date-log-file
      - name: Get the date
        run: date >>date.log
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: date-log-file
          path: date.log


    
