name: Java CI with Gradle

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
         java-version: '11'
         distribution: 'adopt'
         cache: gradle
      - run: chmod +x gradlew
  compile:
    needs: setup
    steps:
      - run: ./gradlew compileJava
  test:
    needs: compile
    steps:
      - run: ./gradlew test
    
