name: github

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker-example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run box version	    
      uses: docker://alpine
      with:
        entrypoint: /opt
        args: version
     


    
