name: github

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testbox:
    runs-on: ubuntu-latest
    container:
      image: azul/zulu-openjdk-alpine:8-jre
    steps:  
    - uses: actions/checkout@v2
    - name: Making gradlew executable
      run: chmod ug+x gradlew
    - name: Running the build
      run: ./gradlew build
     


    
